name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  compile-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: zhutmost/setup-mill@main
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"
          cache-dependency-path: urlopt4s-js/package-lock.json
      - name: Install dependencies
        run: cd urlopt4s-js && npm install webpack-cli --save-dev
      - name: Compile urlopt4s-js
        run: cd urlopt4s-js && npm exec webpack
      - name: Moving bundle
        run: mv urlopt4s-js/dist/main-bundle.mjs urlopt4s/resources/urlopt4s.mjs
      - name: Publish
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME}}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
        run: |
          mill -i mill.scalalib.SonatypeCentralPublishModule/publishAll --shouldRelease false --publishArtifacts 'urlopt4s[_].publishArtifacts'
